const Engine= Matter.Engine;
const World= Matter.World;
const Bodies= Matter.Bodies;
const Constraint= Matter.Constraint


function setup() {

  createCanvas(800,400);
   engine= Engine.create();
   world= engine.world;
   maxDrops=100
   drops=[]
for(i=0; i<maxDrops; i++){
    drops.push(new Drops(random(0,800),random(0,400)))
  }
}

function draw() {
  background(0);
  Engine.update(engine)
  drops[0].display(); drops[0].update()
  drops[1].display(); drops[1].update()
  drops[2].display(); drops[2].update()
  drops[3].display(); drops[3].update()
  drops[4].display(); drops[4].update()
  drops[5].display(); drops[5].update()
  drops[6].display(); drops[6].update()
  drops[7].display(); drops[7].update()
  drops[8].display(); drops[8].update()
  drops[9].display(); drops[9].update()
  drops[10].display(); drops[10].update()
  drops[11].display(); drops[11].update()
  drops[12].display(); drops[12].update()
  drops[13].display(); drops[13].update()
  drops[14].display(); drops[14].update()
  drops[15].display(); drops[15].update()
  drops[16].display(); drops[16].update()
  drops[17].display(); drops[17].update()
  drops[18].display(); drops[18].update()
  drops[19].display(); drops[19].update()
  drops[20].display(); drops[20].update()
  drops[21].display(); drops[21].update()
  drops[22].display(); drops[22].update()
  drops[23].display(); drops[23].update()
  drops[24].display(); drops[24].update()
  drops[25].display(); drops[25].update()
  drops[26].display(); drops[26].update()
  drops[27].display(); drops[27].update()
  drops[28].display(); drops[28].update()
  drops[29].display(); drops[29].update()
  drops[30].display(); drops[30].update()
  drops[31].display(); drops[31].update()
  drops[32].display(); drops[32].update()
  drops[33].display(); drops[33].update()
  drops[34].display(); drops[34].update()
  drops[35].display(); drops[35].update()
  drops[36].display(); drops[36].update()
  drops[37].display(); drops[37].update()
  drops[38].display(); drops[38].update()
  drops[39].display(); drops[39].update()
  drops[40].display(); drops[40].update()
  drops[41].display(); drops[41].update()
  drops[42].display(); drops[42].update()
  drops[43].display(); drops[43].update()
  drops[44].display(); drops[44].update()
  drops[45].display(); drops[45].update()
  drops[46].display(); drops[46].update()
  drops[47].display(); drops[47].update()
  drops[48].display(); drops[48].update()
  drops[49].display(); drops[49].update()
  drops[50].display(); drops[50].update()
  drops[51].display(); drops[51].update()
  drops[52].display(); drops[52].update()
  drops[53].display(); drops[53].update()
  drops[54].display(); drops[54].update()
  drops[55].display(); drops[55].update()
  drops[56].display(); drops[56].update()
  drops[57].display(); drops[57].update()
  drops[58].display(); drops[58].update()
  drops[59].display(); drops[59].update()
  drops[60].display(); drops[60].update()
  drops[61].display(); drops[61].update()
  drops[62].display(); drops[62].update()
  drops[63].display(); drops[63].update()
  drops[64].display(); drops[64].update()
  drops[65].display(); drops[65].update()
  drops[66].display(); drops[66].update()
  drops[67].display(); drops[67].update()
  drops[68].display(); drops[68].update()
  drops[69].display(); drops[69].update()
  drops[70].display(); drops[70].update()
  drops[71].display(); drops[71].update()
  drops[72].display(); drops[72].update()
  drops[73].display(); drops[73].update()
  drops[74].display(); drops[74].update()
  drops[75].display(); drops[75].update()
  drops[76].display(); drops[76].update()
  drops[77].display(); drops[77].update()
  drops[78].display(); drops[78].update()
  drops[79].display(); drops[79].update()
  drops[80].display(); drops[80].update()
  drops[81].display(); drops[81].update()
  drops[82].display(); drops[82].update()
  drops[83].display(); drops[83].update()
  drops[84].display(); drops[84].update()
  drops[85].display(); drops[85].update()
  drops[86].display(); drops[86].update()
  drops[87].display(); drops[87].update()
  drops[88].display(); drops[88].update()
  drops[89].display(); drops[89].update()
  drops[90].display(); drops[90].update()
  drops[91].display(); drops[91].update()
  drops[92].display(); drops[92].update()
  drops[93].display(); drops[93].update()
  drops[94].display(); drops[94].update()
  drops[95].display(); drops[95].update()
  drops[96].display(); drops[96].update()
  drops[97].display(); drops[97].update()
  drops[98].display(); drops[98].update()
  drops[99].display(); drops[99].update()
}